spring.application.name=modum


spring.datasource.url=jdbc:mysql://localhost:3306/modumdb
spring.datasource.username=root
spring.datasource.password=merowni4834

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false